name: Android CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-platform: 'android-30'
          ndk-version: '21.4.7075529'

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v2
        with:
          name: debug-apk

      # Here you might want to add steps for signing your APK and any other necessary processing

      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Github-Actions@v1
        with:
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}
          app-id: ${{ secrets.FIREBASE_APP_ID }}
          groups: 'qa' # Modify this according to your Firebase App Distribution setup
          artifact-path: app-debug.apk
